### ISSUE TITLE
Error. Try bw!help (Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id')

### ISSUE THREAD

**Issue by chrispoupart** [Iqrahaq/BookWorm#3]
When attempting to run `bw!botsetup` from Discord, I get the following error:

```
Error. Try bw!help (Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id')
```

and on the server console, I get this:

```
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/vagrant/code/cogs/Bot.py", line 42, in botsetup
    GUILD = ctx.guild.id
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/vagrant/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/vagrant/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

've been working on getting this working in Docker container on my Raspberry Pi server, and the bot setup is the last step (I hope!) that I can't seem to get working.

I've attempted to follow the instructions to the letter in an Ubuntu 18.04 virtual machine and I get the same error.

**Comment by chrispoupart** [comment]
OK, so reading through the errors and digging into the python a little bit, the problem is that I was direct messaging the bot to set it up, and without sending the message from a "server", there is no Guild, and thus no Guild id attribute.

Sending a message from the actual Discord server to which the bot is joined works.  This should possibly be added to the documentation, and I'll try to include it with my PR that includes a Docker option once I get that properly hammered out.
